### ISSUE TITLE
get firmware version from cver and nver

### ISSUE THREAD

**Issue by Hartie95** [hartmannaf/Free-multi-Patcher#4]
Maybe we should get the firmware version from cver and nver to, so we could separate the types of modules that a patch is modifying( ns for example is a kernel module wich depends on the kernel version while the home menu depends on the cver and the eshop on the nver)
But first I need to find out how to get informations from cver and never.

**Comment by Syphurith** [comment]
Surely this way is better. However i can not find the old link for how to extract contents from `.app` files.
These files can be generated by rxTools decrypt system titles. Or from FunkyCIA maybe (even).

**Comment by Hartie95** [comment]
Would be interesting to know how the system settings application is getting these informations.

**Comment by Syphurith** [comment]
@hartmannaf The one dumped by my rxTools should to be decypted but not. Which then turns out, these `CVer` and `NVer` are stored as encrypted even in NAND. You could just get one `.app` from decrypted NAND partition, and use rxTools to decrypt it with `ncchinfo.bin` and padxorer.
- Dump and Decrypt NAND Image (If already have, just skip this part)
  - Use GW to dump your NAND.bin
  - Use RxTools to generate the FAT16 xorpad
  - Use Padxorer to create the decrypted NAND
  - Use WinImage/UltraISO or other, to mount and unpack the decrypted NAND
- Get the title and decrypt it.
  - Check your `<nand>/title/000400db` for any 16?02 17?02
    - TitleId may differ. You may want to take a look at Title_List on 3dbrew
  - Get the content folder, and find the `.app` files.
  - These `.app` are encrypted, get your rxTools to generate a `ncchinfo.bin` for it.
  - Get ctrtool, and you would need to unpack the file. Something like:
    - `ctrtool -p --romfs=romfs.bin --exefs=exefs.bin --exheader=exheader.bin <file>`
  - Generate xorpad with rxtools, and get the pad for your `.app`.
  - use padxorer to decrypt the `romfs.bin`
  - It is now decrypted. Use ctrtool to unpack. As padxorer output is already `decrypted_romfs.bin`.
    - `ctrtool -t romfs --romfsdir=romfs decrypted_romfs.bin`.
- Now search for a `version.bin` and check it out. For me it contains only 8 bytes.
  - `00 00 19 00 4A 00 00 00` for my 9.8 JPN EmuNAND.

I don't know if there is any easier way for you. The steps above are just manual usage.
I suggest you to ask @dukesrg and even other for homebrew development for this.

**Comment by Syphurith** [comment]
IIRC, there is a special register that could be accessed from CFW.. (ARM9)
But i don't know if there is also a reg for you in ARM11.
NTR just detects the version using HomeMenu one, and that should be included in BootNTR.
Or else you may check TMD for other for the version number. Easier than the f*cking version.bin.
Also contact @Steveice10 for how to use his ctrcommon. There is a osGetKernelVersion function.

**Comment by Hartie95** [comment]
I will lock into BootNTRs detection. But there need to be a clean way to get the firmware Version on arm11 because the system settings application can do it too. But maybe it is done using a service that isn't fully reverse engineered at the moment.

**Comment by Syphurith** [comment]
BootNTR did that using ctrcommon library from Steveice10.

**Comment by Hartie95** [comment]
In BootNTR he seems to check home menus memory at one position, after that I think he is defining the home menu version by himself, depending on the code on that position.

**Comment by Hartie95** [comment]
Thanks to yellows8 release of his themehax installer, im now able to read the cver and nver from nand. It will be included in the next version push to my patchLayout Branch
